package com.smartgrocery.modules.auth.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.annotation.Version;
import org.springframework.data.relational.core.mapping.Column;
import org.springframework.data.relational.core.mapping.Table;

import java.time.Instant;
import java.util.UUID;

// @Table maps this class to the user_account table in PostgreSQL
// This is R2DBC — no @Entity, no JPA, no Hibernate
@Table("user_account")
@Data                   // Lombok — generates getters, setters, equals, hashCode, toString
@Builder                // Lombok — lets us do UserAccount.builder().email("x").build()
@NoArgsConstructor      // Lombok — generates empty constructor (R2DBC requires this)
@AllArgsConstructor     // Lombok — generates constructor with all fields
public class UserAccount {

    // @Id tells R2DBC this is the primary key
    // UUID is generated by PostgreSQL default (uuid_generate_v4()) — not by Java
    @Id
    private UUID id;

    @Column("email")
    private String email;

    @Column("email_verified")
    private Boolean emailVerified;

    @Column("display_name")
    private String displayName;

    @Column("first_name")
    private String firstName;

    @Column("last_name")
    private String lastName;

    @Column("avatar_url")
    private String avatarUrl;

    // Status — ACTIVE, SUSPENDED, LOCKED, DELETED
    // Stored as VARCHAR in DB, mapped as String here
    // We use a separate enum for business logic — not stored as enum in DB
    @Column("status")
    private String status;

    @Column("failed_login_attempts")
    private Short failedLoginAttempts;

    // Tracks where the user is in the onboarding flow
    // ACCOUNT_CREATED → CARD_CONNECTED → CATEGORIES_SET → BUDGET_SET → COMPLETED
    @Column("onboarding_step")
    private String onboardingStep;

    // @Version enables optimistic locking — prevents two requests
    // from overwriting each other's changes simultaneously
    @Version
    private Integer version;

    // @CreatedDate — R2DBC automatically sets this when row is inserted
    @CreatedDate
    @Column("created_at")
    private Instant createdAt;

    // @LastModifiedDate — R2DBC automatically updates this on every save
    @LastModifiedDate
    @Column("updated_at")
    private Instant updatedAt;

    @Column("deleted_at")
    private Instant deletedAt;

    // ── Business logic methods ─────────────────────────────────────────────
    // Keep business rules on the entity itself — not scattered in services

    // Check if account is available for login
    public boolean isActive() {
        return "ACTIVE".equals(this.status) && this.deletedAt == null;
    }

    // Check if account is locked due to too many failed attempts
    public boolean isLocked() {
        return "LOCKED".equals(this.status);
    }

    // Increment failed attempts — called on bad login
    public void incrementFailedAttempts() {
        this.failedLoginAttempts = (short) (this.failedLoginAttempts + 1);
    }

    // Lock the account — called after 5 failed attempts
    public void lock() {
        this.status = "LOCKED";
    }

    // Reset failed attempts on successful login
    public void resetFailedAttempts() {
        this.failedLoginAttempts = 0;
    }

    // Soft delete — never actually deletes the row
    public void softDelete() {
        this.status = "DELETED";
        this.deletedAt = Instant.now();
    }
}
