package com.smartfinvo.modules.analytics.infrastructure.web.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Schema(description = "LLM-generated spending insights for a given date range.")
public class InsightResponse {

    @Schema(description = "List of actionable insights generated by the AI")
    private List<InsightItem> insights;

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    @Builder
    @Schema(description = "A single AI-generated spending insight.")
    public static class InsightItem {

        // OVERSPEND | SAVING | PATTERN | ALERT — maps to AiModulePort.InsightType
        @Schema(description = "Insight type", example = "OVERSPEND",
                allowableValues = {"OVERSPEND", "SAVING", "PATTERN", "ALERT"})
        private String type;

        // Maps to AiModulePort.Insight.finding — short headline
        @Schema(description = "Short headline for this insight", example = "Snack spending up 34%")
        private String title;

        // Maps to AiModulePort.Insight.category — which category triggered this insight
        @Schema(description = "Expense category this insight relates to", example = "snacks")
        private String category;

        // Maps to AiModulePort.Insight.suggestion — the actionable recommendation
        @Schema(description = "Actionable recommendation", example = "Consider setting a $40 monthly snack budget")
        private String recommendation;
    }
}
